### ISSUE TITLE
Not loading table # Grab the latest stock close price 

### ISSUE THREAD

**Issue by harshvarudkar** [kdboller/pythonsp500-robo-advisor-edition#1]
# Grab the latest stock close price 
adj_close_latest = adj_close[adj_close['Date']==stocks_end]
adj_close_latest
this table is showing blank

and it will continue for all below table

**Comment by kdboller** [comment]
Make sure that the last record of data ties to your stocks_end variable.

If your dataframe only goes out to 9/23/2019, but you state that stocks_end = 9/24/2019, then you will not return any data.  stocks_end has to be <= the last record of data, otherwise you'll get an empty table return.
